- mindmapper-backend/README.md
- mindmapper-backend/src/map/controllers/maps.controller.ts
- mindmapper-backend/src/map/entities/mmpMap.entity.ts
- mindmapper-backend/src/map/services/maps.service.ts
- mindmapper-backend/src/map/types.ts
- mindmapper-backend/src/migrations/1640704269037-AddDefaultTimestampToMaps.ts
- mindmapper-backend/src/migrations/1640939564906-AddAdminIdForMaps.ts
- mindmapper-backend/test/db.ts
- mindmapper-frontend/mmp/src/map/types.ts
- mindmapper-frontend/src/app/core/http/http.service.ts
- mindmapper-frontend/src/app/core/services/map-sync/map-sync.service.ts
- mindmapper-frontend/src/app/core/services/map-sync/server-types.ts
- mindmapper-frontend/src/app/core/services/storage/storage.service.ts
- mindmapper-frontend/src/app/modules/application/pages/application/application.component.ts
- mindmapper-frontend/src/app/shared/components/about-modal/about-dialog.component.html
- mindmapper-frontend/src/app/shared/components/about-modal/about-dialog.component.ts
- mindmapper-frontend/src/app/shared/models/cached-map.model.ts
- mindmapper-frontend/src/app/shared/services/dialog/dialog.service.ts
- mindmapper-frontend/src/assets/i18n/de.json
- mindmapper-frontend/src/assets/i18n/en.json
- mindmapper-frontend/src/assets/i18n/es.json
- mindmapper-frontend/src/assets/i18n/fr.json
- mindmapper-frontend/src/assets/i18n/it.json
- mindmapper-frontend/src/assets/i18n/pt-br.json
- mindmapper-frontend/src/assets/i18n/zh-cn.json
- mindmapper-frontend/src/assets/i18n/zh-tw.json
> add button to delete mindmap

- mindmapper-frontend/src/index.html
> fix zoom bug on mobile for color inputs

- mindmapper-frontend/angular.json
- mindmapper-frontend/src/app/shared/components/about-modal/about-dialog.component.ts
- mindmapper-frontend/src/index.html
- mindmapper-frontend/src/main.ts
> add default icons, fix angular setup

- Dockerfile
- README.md
- package.json
- teammapper-backend/package.json
- teammapper-frontend/mmp/src/map/handlers/zoom.ts
- teammapper-frontend/package-lock.json
- teammapper-frontend/package.json
- teammapper-frontend/src/app/core/services/shortcuts/shortcuts.service.ts
- teammapper-frontend/src/app/modules/application/components/toolbar/toolbar.component.ts
- teammapper-frontend/src/app/shared/components/share-dialog/share-dialog.component.html
- teammapper-frontend/src/app/shared/components/share-dialog/share-dialog.component.scss
- teammapper-frontend/src/app/shared/components/share-dialog/share-dialog.component.ts
- teammapper-frontend/src/app/shared/components/share-fallback/share-fallback.component.html
- teammapper-frontend/src/app/shared/components/share-fallback/share-fallback.component.ts
- teammapper-frontend/src/app/shared/services/dialog/dialog.service.ts
- teammapper-frontend/src/app/shared/shared.module.ts
- teammapper-frontend/src/assets/i18n/de.json
- teammapper-frontend/src/assets/i18n/en.json
- teammapper-frontend/src/assets/i18n/es.json
- teammapper-frontend/src/assets/i18n/fr.json
- teammapper-frontend/src/assets/i18n/it.json
- teammapper-frontend/src/assets/i18n/pt-br.json
- teammapper-frontend/src/assets/i18n/zh-cn.json
- teammapper-frontend/src/assets/i18n/zh-tw.json
> improve sharing mechanism e.g. by adding QR codes

- teammapper-frontend/mmp/src/utils/utils.ts
- teammapper-frontend/src/app/core/services/mmp/mmp.service.ts
> fix image and pdf download for safari, fix pdf sizing

- teammapper-backend/src/map/controllers/maps.gateway.ts
- teammapper-backend/src/map/services/maps.service.ts
- teammapper-backend/test/app.e2e-spec.ts
> Fixes bug with node delete and import nodes due to missing order and mapId

- Dockerfile
- package.json
- teammapper-backend/package-lock.json
- teammapper-backend/package.json
- teammapper-frontend/package-lock.json
- teammapper-frontend/package.json
> update npm version and fix security warnings

- teammapper-backend/src/map/controllers/maps.gateway.ts
- teammapper-frontend/mmp/src/map/handlers/nodes.ts
- teammapper-frontend/src/app/core/services/mmp/mmp.service.ts
- teammapper-frontend/src/app/modules/application/pages/application/application.component.ts
> select most recently created node

- teammapper-backend/src/map/services/maps.service.spec.ts
- teammapper-backend/src/map/services/maps.service.ts
> fix delete bug with scheduled deletion job

- README.md
- teammapper-backend/src/map/services/maps.service.ts
- teammapper-backend/src/map/services/tasks.service.ts
> Delete Job: Improved logging, use await to make sure the job finishes

- teammapper-backend/src/config.service.ts
> add sql timeouts to config

- teammapper-backend/src/config.service.ts
- teammapper-backend/src/map/entities/mmpNode.entity.ts
- teammapper-backend/src/migrations/1663839307996-AddIndexToForeignKeys.ts
- teammapper-backend/src/migrations/1663839669273-AddIndexToForeignKeysOnMmpNode.ts
> add index to foreign keys on node

- teammapper-backend/src/jobs/seedMapData.job.ts
- teammapper-frontend/src/app/core/services/map-sync/map-sync.service.ts
- teammapper-frontend/src/app/core/services/shortcuts/shortcuts.service.ts
- teammapper-frontend/src/app/modules/application/pages/application/application.component.ts
- teammapper-frontend/src/app/root-routing.module.ts
- teammapper-frontend/src/assets/i18n/de.json
- teammapper-frontend/src/assets/i18n/en.json
- teammapper-frontend/src/assets/i18n/es.json
- teammapper-frontend/src/assets/i18n/fr.json
- teammapper-frontend/src/assets/i18n/it.json
- teammapper-frontend/src/assets/i18n/pt-br.json
- teammapper-frontend/src/assets/i18n/zh-cn.json
- teammapper-frontend/src/assets/i18n/zh-tw.json
> optimize hotkeys and refactor location flow

- teammapper-frontend/mmp/src/map/handlers/export.ts
- teammapper-frontend/package.json
- teammapper-frontend/src/app/core/services/mmp/mmp.service.ts
- teammapper-frontend/src/app/modules/application/components/toolbar/toolbar.component.html
- teammapper-frontend/src/assets/i18n/de.json
- teammapper-frontend/src/assets/i18n/en.json
- teammapper-frontend/src/assets/i18n/es.json
- teammapper-frontend/src/assets/i18n/fr.json
- teammapper-frontend/src/assets/i18n/it.json
- teammapper-frontend/src/assets/i18n/pt-br.json
- teammapper-frontend/src/assets/i18n/zh-cn.json
- teammapper-frontend/src/assets/i18n/zh-tw.json
> fix pdf bad quality and also add svg download of map

- teammapper-backend/src/map/services/maps.service.ts
- teammapper-frontend/mmp/src/map/options.ts
- teammapper-frontend/mmp/src/utils/utils.ts
- teammapper-frontend/src/app/core/services/mmp/mmp.service.ts
> start with empty node with active cursor

- teammapper-frontend/src/app/core/services/shortcuts/shortcuts.service.ts
> add backspace hotkey to remove nodes

- teammapper-frontend/src/app/core/services/utils/utils.service.ts
- teammapper-frontend/src/app/modules/application/components/toolbar/toolbar.component.html
- teammapper-frontend/src/app/modules/application/components/toolbar/toolbar.component.ts
> remove fullscreen button as this is provided by the browser

- teammapper-frontend/src/assets/data/settings.json
> adjust settings to use empty node name as default

- README.md
- docker-compose-prod.yml
- teammapper-backend/package-lock.json
- teammapper-backend/package.json
- teammapper-backend/src/config.service.ts
- teammapper-backend/src/data-source.ts
- teammapper-backend/src/ormconfig.ts
> fix typeorm interface

- Dockerfile
- README.md
- entrypoint.prod.sh
> only run migrations if db exists

- README.md
> fix readme port in setup instructions

- .github/workflows/release.yml
> add image build push to GitHub

- teammapper-frontend/src/app/core/services/map-sync/map-sync.service.ts
- teammapper-frontend/src/app/modules/application/components/toolbar/toolbar.component.ts
- teammapper-frontend/src/app/modules/application/pages/application/application.component.ts
> ignore empty link

- teammapper-backend/package.json
- teammapper-backend/src/jobs/deleteMaps.job.ts
- teammapper-backend/src/map/entities/mmpNode.entity.ts
- teammapper-backend/src/map/services/maps.service.spec.ts
- teammapper-backend/src/map/services/maps.service.ts
- teammapper-backend/src/map/services/tasks.service.ts
- teammapper-backend/src/migrations/1679478438937-AddLastModifiedToNodes.ts
- teammapper-backend/test/app.e2e-spec.ts
- teammapper-backend/test/db.ts
- teammapper-backend/test/helper.ts
> Use node lastModified  instead of map lastModified for cleanup

- teammapper-frontend/src/app/shared/components/about-modal/about-dialog.component.html
- teammapper-frontend/src/app/shared/components/about-modal/about-dialog.component.scss
- teammapper-frontend/src/app/shared/components/share-dialog/share-dialog.component.html
- teammapper-frontend/src/environments/environment.prod.ts
- teammapper-frontend/src/environments/environment.ts
- teammapper-frontend/src/styles.scss
> smaller design adjustments for info modal

- teammapper-frontend/karma.conf.js
- teammapper-frontend/src/app/core/services/settings/settings.service.spec.ts
> refactor settings unit test

- teammapper-frontend/src/app/modules/about/components/footer/footer.component.html
- teammapper-frontend/src/app/modules/about/components/header/header.component.html
- teammapper-frontend/src/app/modules/about/components/header/header.component.ts
- teammapper-frontend/src/app/modules/about/components/jumbotron/jumbotron.component.html
- teammapper-frontend/src/app/modules/about/pages/about/about.component.html
- teammapper-frontend/src/app/root-routing.module.ts
- teammapper-frontend/src/assets/i18n/de.json
- teammapper-frontend/src/assets/i18n/en.json
- teammapper-frontend/src/assets/i18n/es.json
- teammapper-frontend/src/assets/i18n/fr.json
- teammapper-frontend/src/assets/i18n/it.json
- teammapper-frontend/src/assets/i18n/pt-br.json
- teammapper-frontend/src/assets/i18n/zh-cn.json
- teammapper-frontend/src/assets/i18n/zh-tw.json
- teammapper-frontend/src/environments/environment.prod.ts
- teammapper-frontend/src/environments/environment.ts
> improve start page

- README.md
- teammapper-frontend/src/assets/i18n/de.json
> add teammapper.org link to readme

- teammapper-frontend/mmp/src/map/handlers/export.ts
> improve and fix svg img export font problem

- teammapper-frontend/mmp/src/map/handlers/export.ts
> fix: export missing images bug on safari workaround

- teammapper-backend/src/map/entities/mmpNode.entity.ts
- teammapper-backend/src/map/services/maps.service.ts
- teammapper-backend/src/map/types.ts
- teammapper-backend/src/map/utils/clientServerMapping.ts
- teammapper-backend/src/migrations/1701777634545-AddDetachedPropertyToNodes.ts
- teammapper-backend/test/app.e2e-spec.ts
- teammapper-frontend/mmp/src/map/handlers/draw.ts
- teammapper-frontend/mmp/src/map/handlers/history.ts
- teammapper-frontend/mmp/src/map/handlers/nodes.ts
- teammapper-frontend/mmp/src/map/models/node.ts
- teammapper-frontend/mmp/src/map/options.ts
- teammapper-frontend/src/app/core/services/map-sync/map-sync.service.ts
- teammapper-frontend/src/app/core/services/mmp/mmp.service.ts
- teammapper-frontend/src/app/modules/application/components/toolbar/toolbar.component.html
- teammapper-frontend/src/app/modules/application/components/toolbar/toolbar.component.ts
- teammapper-frontend/src/assets/i18n/de.json
- teammapper-frontend/src/assets/i18n/en.json
- teammapper-frontend/src/assets/i18n/es.json
- teammapper-frontend/src/assets/i18n/fr.json
- teammapper-frontend/src/assets/i18n/it.json
- teammapper-frontend/src/assets/i18n/pt-br.json
- teammapper-frontend/src/assets/i18n/zh-cn.json
- teammapper-frontend/src/assets/i18n/zh-tw.json
> add detached nodes

- teammapper-frontend/src/app/core/services/mmp/mmp.service.ts
> disable add node for detached nodes

- teammapper-frontend/mmp/src/map/handlers/export.ts
> improve image export quality

- teammapper-frontend/mmp/src/map/handlers/export.ts
> fix firefox image export text elements offset

- teammapper-frontend/src/app/modules/application/components/dialog-share/dialog-share.component.ts
> fix qr code on android as it is cut off

- Dockerfile
- docker-compose-prod.yml
- docker-compose.yml
- teammapper-frontend/mmp/src/map/handlers/export.ts
- teammapper-frontend/package-lock.json
- teammapper-frontend/package.json
> fix line break in image export

- teammapper-frontend/mmp/src/map/handlers/export.ts
- teammapper-frontend/package-lock.json
- teammapper-frontend/package.json
> fix missing text from export

- teammapper-frontend/src/app/core/services/pictograms/pictogram.service.spec.ts
- teammapper-frontend/src/app/core/services/pictograms/pictogram.service.ts
- teammapper-frontend/src/app/modules/application/components/dialog-pictograms/dialog-pictograms.component.html
- teammapper-frontend/src/app/modules/application/components/dialog-pictograms/dialog-pictograms.component.scss
- teammapper-frontend/src/assets/i18n/de.json
- teammapper-frontend/src/assets/i18n/en.json
- teammapper-frontend/src/assets/i18n/es.json
- teammapper-frontend/src/assets/i18n/fr.json
- teammapper-frontend/src/assets/i18n/it.json
- teammapper-frontend/src/assets/i18n/pt-br.json
- teammapper-frontend/src/assets/i18n/zh-cn.json
- teammapper-frontend/src/assets/i18n/zh-tw.json
- teammapper-frontend/src/environments/environment.prod.ts
> picto minor improvements

- README.md
- teammapper-backend/package-lock.json
- teammapper-backend/package.json
- teammapper-backend/src/main.ts
- teammapper-frontend/src/environments/environment.prod.ts
- teammapper-frontend/src/proxy.conf.json
> add proxy for pictos to ensure GDPR compliency

- teammapper-backend/src/map/controllers/maps.gateway.ts
- teammapper-backend/src/map/services/maps.service.ts
> harden backend against crashes

- teammapper-backend/package.json
- teammapper-backend/tsconfig.json
> fix line numbers crashes

- teammapper-backend/src/map/controllers/maps.gateway.spec.ts
- teammapper-backend/src/map/controllers/maps.gateway.ts
- teammapper-backend/src/map/services/maps.service.spec.ts
- teammapper-backend/src/map/services/maps.service.ts
- teammapper-backend/src/map/types.ts
- teammapper-backend/test/app.e2e-spec.ts
- teammapper-frontend/mmp/src/map/handlers/copy-paste.ts
- teammapper-frontend/mmp/src/map/handlers/events.ts
- teammapper-frontend/mmp/src/map/handlers/nodes.ts
- teammapper-frontend/src/app/core/services/map-sync/map-sync.service.ts
- teammapper-frontend/src/app/core/services/map-sync/server-types.ts
> fix disappearing nodes when pasting Is used

- teammapper-backend/src/main.ts
- teammapper-backend/src/map/services/maps.service.ts
- teammapper-frontend/mmp/src/map/handlers/nodes.ts
- teammapper-frontend/src/app/core/services/map-sync/map-sync.service.ts
> refactorings, e.g. nodes creation in backend

- teammapper-backend/src/map/services/maps.service.ts
- teammapper-frontend/src/app/modules/application/components/dialog-pictograms/dialog-pictograms.component.html
- teammapper-frontend/src/app/modules/application/components/dialog-pictograms/dialog-pictograms.component.ts
> fix wrong aspect ratio for pictos

- teammapper-frontend/mmp/src/map/handlers/export.ts
> fix line break bug within export due to line break conversion in tspan

- teammapper-backend/src/config.service.ts
- teammapper-backend/src/jobs/deleteMaps.job.ts
- teammapper-backend/src/jobs/seedMapData.job.ts
- teammapper-backend/src/map/controllers/maps.controller.ts
- teammapper-backend/src/map/controllers/maps.gateway.spec.ts
- teammapper-backend/src/map/controllers/maps.gateway.ts
- teammapper-backend/src/map/guards/edit.guard.ts
- teammapper-backend/src/map/services/maps.service.spec.ts
- teammapper-backend/src/map/services/maps.service.ts
- teammapper-backend/src/map/services/tasks.service.ts
- teammapper-backend/src/map/utils/clientServerMapping.ts
- teammapper-backend/test/app.e2e-spec.ts
- teammapper-backend/test/db.ts
- teammapper-backend/tsconfig.json
- teammapper-frontend/src/app/core/services/dialog/dialog.service.ts
- teammapper-frontend/src/app/modules/application/application.module.ts
- teammapper-frontend/src/app/modules/application/components/dialog-pictograms/dialog-pictograms.component.html
- teammapper-frontend/src/app/modules/application/components/toolbar/toolbar.component.html
- teammapper-frontend/src/app/shared/shared.module.ts
> add picto search button

- teammapper-backend/package-lock.json
- teammapper-backend/package.json
- teammapper-backend/src/map/controllers/maps.controller.ts
- teammapper-backend/src/map/services/maps.service.ts
- teammapper-backend/src/map/services/uuid.error.ts
> return 404 if uuid is in the wrong format

- teammapper-backend/src/map/controllers/maps.controller.spec.ts
> Add test coverage to maps.controller.spec.ts

- teammapper-backend/test/app.e2e-spec.ts
- teammapper-frontend/angular.json
> E2E tests have an increased failure rate

- teammapper-frontend/angular.json
- teammapper-frontend/mmp/src/map/handlers/nodes.ts
- teammapper-frontend/src/app/core/services/mmp/mmp.service.ts
> Detached nodes after creation at different positions

- teammapper-backend/src/map/controllers/maps.controller.spec.ts
- teammapper-backend/src/map/utils/tests/mapFactories.ts
- teammapper-frontend/angular.json
> Test factory to create maps and nodes

- teammapper-backend/src/map/controllers/maps.controller.ts
- teammapper-frontend/angular.json
- teammapper-frontend/src/app/core/services/map-sync/map-sync.service.ts
- teammapper-frontend/src/app/guards/toast.guard.ts
- teammapper-frontend/src/app/modules/application/pages/application/application.component.ts
- teammapper-frontend/src/assets/i18n/de.json
- teammapper-frontend/src/assets/i18n/en.json
- teammapper-frontend/src/assets/i18n/es.json
- teammapper-frontend/src/assets/i18n/fr.json
- teammapper-frontend/src/assets/i18n/it.json
- teammapper-frontend/src/assets/i18n/pt-br.json
- teammapper-frontend/src/assets/i18n/zh-cn.json
- teammapper-frontend/src/assets/i18n/zh-tw.json
> Display an error when map cannot be found

- teammapper-frontend/src/app/core/services/mmp/mmp.service.ts
- teammapper-frontend/src/assets/i18n/de.json
- teammapper-frontend/src/assets/i18n/en.json
- teammapper-frontend/src/assets/i18n/es.json
- teammapper-frontend/src/assets/i18n/fr.json
- teammapper-frontend/src/assets/i18n/it.json
- teammapper-frontend/src/assets/i18n/pt-br.json
- teammapper-frontend/src/assets/i18n/zh-cn.json
- teammapper-frontend/src/assets/i18n/zh-tw.json
> Missing toast when trying to copy root node

- teammapper-frontend/src/assets/i18n/zh-cn.json
- teammapper-frontend/src/assets/i18n/zh-tw.json
> Bad merge with language files

- teammapper-frontend/src/app/guards/toast.guard.ts
- teammapper-frontend/src/app/modules/application/components/dialog-share/dialog-share.component.ts
> History bugs when copying map

- teammapper-frontend/mmp/src/map/handlers/copy-paste.ts
- teammapper-frontend/mmp/src/map/handlers/nodes.ts
- teammapper-frontend/src/app/core/services/map-sync/map-sync.service.ts
- teammapper-frontend/src/app/core/services/mmp/mmp.service.ts
> Add optional boolean argument to updateNode() to skip updating history

- package.json
- teammapper-backend/package-lock.json
- teammapper-backend/package.json
- teammapper-frontend/package-lock.json
- teammapper-frontend/package.json
> Node versions in package files are inconsistent

- teammapper-backend/package-lock.json
- teammapper-backend/package.json
- teammapper-frontend/package-lock.json
- teammapper-frontend/package.json
> Upgrade @types/uuid package to dependency

- teammapper-frontend/mmp/src/map/handlers/nodes.ts
> Refactor methods in nodes.ts to return consistent values

- Dockerfile
> Update Docker image

- teammapper-backend/src/jobs/seedMapData.job.ts
- teammapper-backend/src/map/entities/mmpMap.entity.ts
- teammapper-backend/src/map/entities/mmpNode.entity.ts
- teammapper-backend/src/map/services/maps.service.spec.ts
- teammapper-backend/src/map/services/maps.service.ts
- teammapper-backend/src/map/types.ts
- teammapper-backend/src/map/utils/clientServerMapping.ts
- teammapper-backend/src/map/utils/tests/mapFactories.ts
- teammapper-backend/src/migrations/1724314314717-AddCreatedAtToMap.ts
- teammapper-backend/src/migrations/1724314435583-AddCreatedAtToNode.ts
- teammapper-backend/src/migrations/1724325535133-AddDefaultToCreatedAtMmpMap.ts
- teammapper-backend/src/migrations/1724325567562-AddDefaultToCreatedAtMmpNode.ts
- teammapper-backend/test/app.e2e-spec.ts
- teammapper-frontend/mmp/src/map/types.ts
- teammapper-frontend/src/app/core/services/map-sync/map-sync.service.ts
- teammapper-frontend/src/app/core/services/map-sync/server-types.ts
- teammapper-frontend/src/app/shared/models/cached-map.model.ts
> Add createdAt date time to maps

- teammapper-backend/src/map/entities/mmpMap.entity.ts
- teammapper-backend/src/map/entities/mmpNode.entity.ts
> add nullable option to createdAt fields

- teammapper-frontend/mmp/src/map/handlers/nodes.ts
> Bug: Adding a free node isn't working anymore

- teammapper-backend/src/map/controllers/maps.gateway.ts
- teammapper-backend/src/map/services/maps.service.ts
> CreatedAt on table 'nodes' gets modified on update

- teammapper-frontend/src/app/core/services/shortcuts/shortcuts.service.ts
- teammapper-frontend/src/app/modules/application/components/floating-buttons/floating-buttons.component.html
> Add back zoom buttons and shortcuts

- teammapper-frontend/src/assets/i18n/zh-cn.json
Complete missing Chinese translations in zh-cn.json
> Complete missing Chinese translations in zh-cn.json

- teammapper-frontend/mmp/src/map/handlers/draw.ts
> Fix warning non-passive event handler

- teammapper-backend/src/map/services/maps.service.spec.ts
- teammapper-backend/src/map/services/maps.service.ts
> Chore: Catch FK exception

- teammapper-frontend/mmp/src/map/handlers/history.ts
> Add client-side rollback during snapshot import

- teammapper-frontend/mmp/src/map/handlers/draw.ts
- teammapper-frontend/mmp/src/map/handlers/nodes.ts
- teammapper-frontend/mmp/src/map/models/node.ts
- teammapper-frontend/mmp/src/map/options.ts
> Remove text decoration from frontend

- teammapper-backend/package-lock.json
- teammapper-backend/package.json
- teammapper-backend/src/map/entities/mmpMap.entity.ts
- teammapper-backend/src/map/entities/mmpNode.entity.ts
- teammapper-backend/src/map/services/maps.service.ts
- teammapper-backend/src/map/utils/clientServerMapping.ts
- teammapper-backend/test/app.e2e-spec.ts
- teammapper-frontend/src/app/core/services/mmp/mmp.service.ts
> Add validations before nodes are saved

- teammapper-backend/src/map/controllers/maps.controller.spec.ts
- teammapper-backend/src/map/controllers/maps.controller.ts
- teammapper-backend/src/map/services/maps.service.spec.ts
- teammapper-backend/src/map/services/maps.service.ts
- teammapper-frontend/package.json
> fix incorrect UUID crash during lookup of a map

- teammapper-backend/src/filters/global-exception.filter.ts
- teammapper-backend/src/main.ts
> Backend Typescript Build fails

- teammapper-backend/src/filters/global-exception.filter.ts
> Global Exception Handler logs 404 Not Found

- .github/workflows/ci.yml
- teammapper-backend/package.json
- teammapper-frontend/package.json
- teammapper-frontend/src/app/core/services/pictograms/pictogram.service.spec.ts
- teammapper-frontend/tsconfig.json
> add backend and frontend build check

- teammapper-frontend/.browserslistrc
- teammapper-frontend/src/app/modules/about/components/jumbotron/jumbotron.component.html
- teammapper-frontend/src/app/modules/about/components/jumbotron/jumbotron.component.scss
> fix landing page and safari 16

- teammapper-frontend/mmp/src/map/handlers/draw.ts
- teammapper-frontend/mmp/src/map/models/node.ts
- teammapper-frontend/mmp/src/map/options.ts
- teammapper-frontend/src/app/modules/about/components/footer/footer.component.spec.ts
- teammapper-frontend/src/app/modules/application/pages/settings/settings.component.html
- teammapper-frontend/src/app/modules/application/pages/settings/settings.component.scss
- teammapper-frontend/src/app/shared/models/settings.model.ts
- teammapper-frontend/src/assets/data/settings.json
- teammapper-frontend/src/assets/i18n/de.json
- teammapper-frontend/src/assets/i18n/en.json
- Sets the color of links to black
- Adds an option to show linktexts instead of link icons
> Fix invisible links #677

- teammapper-frontend/src/app/modules/application/components/toolbar/toolbar.component.html
- teammapper-frontend/src/assets/i18n/de.json
- teammapper-frontend/src/assets/i18n/en.json
- teammapper-frontend/src/assets/i18n/es.json
- teammapper-frontend/src/assets/i18n/fr.json
- teammapper-frontend/src/assets/i18n/it.json
- teammapper-frontend/src/assets/i18n/pt-br.json
- teammapper-frontend/src/assets/i18n/zh-cn.json
- teammapper-frontend/src/assets/i18n/zh-tw.json
Closes #700 and adds a few tooltips to the toolbar buttons
> #700 deactivate icons in readonly mode

- teammapper-frontend/src/app/core/services/map-sync/map-sync.service.ts
> Limit time period where socket.io tries to reconnect

- teammapper-backend/src/app.module.ts
- teammapper-backend/src/main.ts
Serve static assets directly from nestjs instead of using angular router
Closes #922
> Handling of missing assets in nestjs for production

- Dockerfile
- teammapper-frontend/.browserslistrc
- teammapper-frontend/angular.json
- teammapper-frontend/package.json
> Startup Warnings
